"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { useToast } from "@/components/toast-provider";

export type TodoItem = { id:string; title:string; due_date:string; list_type:"daily"|"weekly"; is_completed:boolean; completed_at:string|null; recurrence_group_id:string|null; recurrence_rule:string; recurrence_days:number[]; reminder_time:string|null };
const longDay=(key:string)=>new Intl.DateTimeFormat("en-US",{weekday:"long",timeZone:"UTC"}).format(new Date(`${key}T00:00:00Z`));
const shortDate=(key:string)=>new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",timeZone:"UTC"}).format(new Date(`${key}T00:00:00Z`));

export default function TodoBoard({items:initialItems,today,view}:{items:TodoItem[];today:string;view:"today"|"week"|"month"}){
 const [items,setItems]=useState(initialItems),[busy,setBusy]=useState<string|null>(null);const router=useRouter(),{showToast}=useToast();
 useEffect(()=>setItems(initialItems),[initialItems]);
 const groups=useMemo(()=>Object.entries(items.reduce<Record<string,TodoItem[]>>((all,item)=>{(all[item.due_date]??=[]).push(item);return all},{})),[items]);
 const completed=items.filter(item=>item.is_completed).length,pending=items.length-completed;
 async function toggle(item:TodoItem){const next=!item.is_completed;setBusy(item.id);setItems(all=>all.map(row=>row.id===item.id?{...row,is_completed:next}:row));const {error}=await createClient().from("todos").update({is_completed:next,completed_at:next?new Date().toISOString():null}).eq("id",item.id);setBusy(null);if(error){setItems(all=>all.map(row=>row.id===item.id?item:row));showToast("That task could not be updated.","error")}else{showToast(next?"Task completed.":"Task reopened.");router.refresh()}}
 async function remove(item:TodoItem){if(!window.confirm(`Remove “${item.title}” from this day?`))return;setBusy(item.id);const {error}=await createClient().from("todos").delete().eq("id",item.id);setBusy(null);if(error){showToast("That task could not be removed.","error");return}setItems(all=>all.filter(row=>row.id!==item.id));showToast("Task removed.");router.refresh()}
 return <div className="mt-7 grid gap-5 lg:grid-cols-[220px_1fr]"><aside className="rounded-3xl border border-[#ded8ea] bg-gradient-to-br from-[#f4f0fa] to-white p-5 shadow-[0_14px_38px_-28px_#4e3a7180] lg:self-start"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#e6def3] text-xl">✓</span><h2 className="mt-5 text-lg font-semibold">{view==="today"?"Today’s list":view==="week"?"This week":"This month"}</h2><p className="mt-1 text-sm text-gray-500">Keep the list light and finish what matters.</p><div className="mt-5 grid grid-cols-2 gap-2"><div className="rounded-2xl bg-white p-3"><strong className="block text-2xl text-[#66528c]">{pending}</strong><span className="text-xs text-gray-500">Remaining</span></div><div className="rounded-2xl bg-white p-3"><strong className="block text-2xl text-[#45634c]">{completed}</strong><span className="text-xs text-gray-500">Done</span></div></div>{items.length>0&&<div className="mt-5 h-2 overflow-hidden rounded-full bg-[#e8e2ef]"><div className="h-full rounded-full bg-[#8068aa] transition-all" style={{width:`${completed/items.length*100}%`}}/></div>}<Link href="/calendar" className="mt-5 flex w-full items-center justify-center rounded-xl border border-[#cfc6df] bg-white px-4 py-2.5 text-sm font-semibold text-[#66528c]">Manage in Calendar</Link></aside>
 <section className="overflow-hidden rounded-3xl border border-[#ded8ea] bg-white shadow-[0_14px_38px_-28px_#4e3a7180]">{!items.length?<div className="px-6 py-20 text-center"><div className="text-4xl">✨</div><h3 className="mt-4 text-lg font-semibold">You’re all clear</h3><p className="mt-2 text-sm text-gray-500">Choose a day in Calendar when you want to add a task.</p><Link href="/calendar" className="mt-5 inline-flex rounded-xl bg-[#6d5796] px-5 py-3 text-sm font-semibold text-white">Open Calendar</Link></div>:<div className="divide-y divide-[#f0edf5]">{groups.map(([date,dayItems])=><div key={date} className="p-5 sm:p-6"><div className="mb-4 flex items-baseline gap-2"><h3 className="font-semibold text-[#55426f]">{date===today?"Today":longDay(date)}</h3><span className="text-xs text-gray-400">{shortDate(date)}</span></div><div className="space-y-3">{dayItems.map(item=><article key={item.id} className={`group flex items-center gap-3 rounded-2xl border px-4 py-3.5 transition ${item.is_completed?"border-[#e8e3ed] bg-[#faf9fc]":"border-[#ddd5e8] bg-white shadow-[0_8px_22px_-18px_#4e3a71] hover:border-[#b9aecb]"}`}><button disabled={busy===item.id} onClick={()=>toggle(item)} aria-label={item.is_completed?`Mark ${item.title} incomplete`:`Mark ${item.title} complete`} className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-lg border text-xs transition ${item.is_completed?"border-[#8068aa] bg-[#8068aa] text-white":"border-[#b9aecb] bg-[#fbfaff] hover:bg-[#eeeafd]"}`}>{item.is_completed?"✓":""}</button><button disabled={busy===item.id} onClick={()=>toggle(item)} className={`min-w-0 flex-1 text-left text-sm font-medium ${item.is_completed?"text-gray-400 line-through":"text-[#30283d]"}`}>{item.title}</button>{item.recurrence_rule!=="none"&&<span title="Repeating task" className="rounded-lg bg-[#eeeafd] px-2 py-1 text-xs text-[#8068aa]">↻</span>}{item.reminder_time&&<span title={`Reminder ${item.reminder_time.slice(0,5)}`} className="text-sm">🔔</span>}<button disabled={busy===item.id} onClick={()=>remove(item)} aria-label={`Remove ${item.title}`} className="flex h-8 w-8 items-center justify-center rounded-lg text-gray-400 transition hover:bg-red-50 hover:text-red-600">×</button></article>)}</div></div>)}</div>}</section></div>
}
