"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createPortal } from "react-dom";
import MomentumSelect from "@/components/momentum-select";
import { createClient } from "@/lib/supabase/client";
import { shiftDateKey } from "@/lib/date-utils";
import { useToast } from "@/components/toast-provider";

export type CalendarTodo={id:string;title:string;due_date:string;list_type:"daily"|"weekly";is_completed:boolean;completed_at:string|null;recurrence_group_id:string|null;recurrence_rule:string;recurrence_days:number[];reminder_time:string|null};
export type CalendarGoal={id:string;name:string;icon:string|null;goal_schedules:{day_of_week:number}[]};
type Repeat="none"|"daily"|"weekdays"|"weekly";
const formatDate=(key:string)=>new Intl.DateTimeFormat("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(`${key}T00:00:00Z`));
const weekday=(key:string)=>new Date(`${key}T00:00:00Z`).getUTCDay()||7;
function occurrenceDates(start:string,end:string,repeat:Repeat){const dates:string[]=[];for(let key=start;key<=end&&dates.length<400;key=shiftDateKey(key,1)){const day=weekday(key);if((repeat==="none"&&key===start)||repeat==="daily"||(repeat==="weekdays"&&day<=5)||(repeat==="weekly"&&day===weekday(start)))dates.push(key);if(repeat==="none")break}return dates}

export default function CalendarGrid({userId,month,title,today,days,previousMonth,nextMonth,todos:initialTodos,goals,hasError}:{userId:string;month:string;title:string;today:string;days:string[];previousMonth:string;nextMonth:string;todos:CalendarTodo[];goals:CalendarGoal[];hasError:boolean}){
 const [mounted,setMounted]=useState(false),[todos,setTodos]=useState(initialTodos),[selected,setSelected]=useState<string|null>(null),[task,setTask]=useState(""),[repeat,setRepeat]=useState<Repeat>("none"),[repeatUntil,setRepeatUntil]=useState(""),[reminder,setReminder]=useState(""),[busy,setBusy]=useState(false),[removing,setRemoving]=useState<CalendarTodo|null>(null); const router=useRouter(),{showToast}=useToast();
 useEffect(()=>{setMounted(true);setTodos(initialTodos)},[initialTodos]);
 const selectedTodos=useMemo(()=>todos.filter(i=>i.due_date===selected),[todos,selected]); const selectedGoals=selected?goals.filter(g=>g.goal_schedules.some(s=>s.day_of_week===weekday(selected))):[];
 async function toggle(item:CalendarTodo){const next=!item.is_completed;setTodos(all=>all.map(row=>row.id===item.id?{...row,is_completed:next}:row));const {error}=await createClient().from("todos").update({is_completed:next,completed_at:next?new Date().toISOString():null}).eq("id",item.id);if(error){setTodos(all=>all.map(row=>row.id===item.id?item:row));showToast("That task could not be updated.","error")}else showToast(next?"Task completed.":"Task reopened.")}
 async function addTask(){if(!selected||!task.trim())return;setBusy(true);const end=repeat==="none"?selected:(repeatUntil||shiftDateKey(selected,90)),group=repeat==="none"?null:crypto.randomUUID(),dates=occurrenceDates(selected,end,repeat);const rows=dates.map(date=>({user_id:userId,title:task.trim(),list_type:"daily",due_date:date,recurrence_group_id:group,recurrence_rule:repeat,recurrence_days:repeat==="weekly"?[weekday(selected)]:[],reminder_time:reminder||null}));const {data,error}=await createClient().from("todos").insert(rows).select("id,title,due_date,list_type,is_completed,completed_at,recurrence_group_id,recurrence_rule,recurrence_days,reminder_time");setBusy(false);if(error){showToast("That task could not be added.","error");return}setTodos(all=>[...all,...((data??[]) as CalendarTodo[])]);setTask("");setReminder("");setRepeat("none");setRepeatUntil("");showToast(dates.length>1?"Repeating tasks added.":"Task added.");router.refresh()}
 async function remove(scope:"one"|"future"|"all"){if(!removing)return;setBusy(true);let query=createClient().from("todos").delete().eq("user_id",userId);if(scope==="one"||!removing.recurrence_group_id)query=query.eq("id",removing.id);else{query=query.eq("recurrence_group_id",removing.recurrence_group_id);if(scope==="future")query=query.gte("due_date",removing.due_date)}const {error}=await query;setBusy(false);if(error){showToast("That task could not be removed.","error");return}setTodos(all=>all.filter(item=>(scope==="one"||!removing.recurrence_group_id)?item.id!==removing.id:item.recurrence_group_id!==removing.recurrence_group_id||(scope==="future"&&item.due_date<removing.due_date)));setRemoving(null);showToast("Task removed.");router.refresh()}
 return <main className="min-h-screen text-[#171717]"><div className="mx-auto max-w-7xl px-4 py-7 sm:px-8 lg:px-10 lg:py-12"><header><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#6c8772]">Calendar</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Plan at a glance</h1><p className="mt-2 text-gray-500">Choose a date to view or manage its tasks.</p></header>
 {hasError?<div role="alert" className="mt-8 rounded-3xl border border-red-200 bg-white p-7 text-sm text-red-700">Could not load the calendar. Refresh and try again.</div>:<section className="mt-7 overflow-hidden rounded-3xl border border-[#dfe6d9] bg-white shadow-[0_12px_35px_-24px_#294d3b80]"><div className="flex items-center justify-between border-b border-[#edf0e9] p-4 sm:p-6"><Link aria-label="Previous month" href={`/calendar?month=${previousMonth}`} className="flex h-10 w-10 items-center justify-center rounded-xl border border-[#dce7de]">←</Link><div className="text-center"><h2 className="text-xl font-semibold">{title}</h2>{month!==today.slice(0,7)&&<Link href="/calendar" className="text-xs text-[#45634c] underline">This month</Link>}</div><Link aria-label="Next month" href={`/calendar?month=${nextMonth}`} className="flex h-10 w-10 items-center justify-center rounded-xl border border-[#dce7de]">→</Link></div><div className="overflow-x-auto"><div className="min-w-[760px]"><div className="grid grid-cols-7 border-b border-[#edf0e9] bg-[#f8faf5]">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(day=><div key={day} className="py-3 text-center text-xs font-semibold text-[#74816f]">{day}</div>)}</div><div className="grid grid-cols-7">{days.map(date=>{const dayTodos=todos.filter(i=>i.due_date===date),dayGoals=goals.filter(g=>g.goal_schedules.some(s=>s.day_of_week===weekday(date))),inMonth=date.slice(0,7)===month;return <button key={date} onClick={()=>setSelected(date)} className={`min-h-32 border-b border-r border-[#edf0e9] p-2.5 text-left transition hover:bg-[#faf8fd] ${inMonth?"bg-white":"bg-[#f8faf5]"}`}><span className={`flex h-7 w-7 items-center justify-center rounded-full text-xs font-semibold ${date===today?"bg-[#294d3b] text-white":inMonth?"text-gray-700":"text-gray-400"}`}>{Number(date.slice(-2))}</span><div className="mt-2 space-y-1">{dayTodos.slice(0,2).map(item=><div key={item.id} className="truncate rounded-lg bg-[#eeeafd] px-2 py-1 text-[10px] text-[#66528c]"><span className={item.is_completed?"line-through opacity-60":""}>{item.is_completed?"✓ ":item.recurrence_rule!=="none"?"↻ ":"• "}{item.title}</span></div>)}{dayGoals.slice(0,1).map(goal=><div key={goal.id} className="truncate rounded-lg bg-[#eaf2e9] px-2 py-1 text-[10px] text-[#45634c]">{goal.icon||"🎯"} {goal.name}</div>)}{dayTodos.length+dayGoals.length>3&&<p className="px-2 text-[10px] text-gray-400">+{dayTodos.length+dayGoals.length-3} more</p>}</div></button>})}</div></div></div><div className="flex gap-5 border-t border-[#edf0e9] px-5 py-4 text-xs text-gray-500"><span><i className="mr-2 inline-block h-2.5 w-2.5 rounded bg-[#cfc2e4]"/>To Dos</span><span><i className="mr-2 inline-block h-2.5 w-2.5 rounded bg-[#bfd2bf]"/>Goals</span></div></section>}
 {mounted&&selected&&createPortal(<div className="fixed inset-0 z-50 flex items-end justify-center bg-[#18251dc0] sm:items-center sm:p-5" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><section role="dialog" aria-modal="true" className="max-h-[92vh] w-full overflow-y-auto rounded-t-3xl bg-white p-5 shadow-2xl sm:max-w-xl sm:rounded-3xl sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#756099]">Day plan</p><h2 className="mt-1 text-2xl font-semibold">{formatDate(selected)}</h2></div><button onClick={()=>setSelected(null)} aria-label="Close" className="flex h-10 w-10 items-center justify-center rounded-xl bg-gray-100 text-xl">×</button></div><div className="mt-6 space-y-2">{!selectedTodos.length&&<p className="rounded-2xl bg-[#faf9fc] p-4 text-sm text-gray-500">No To Dos for this day yet.</p>}{selectedTodos.map(item=><div key={item.id} className="flex items-center gap-3 rounded-2xl border border-[#ebe6f2] bg-[#fbfaff] p-3"><button onClick={()=>toggle(item)} className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-lg border ${item.is_completed?"border-[#8068aa] bg-[#8068aa] text-white":"border-[#b9aecb] bg-white"}`}>{item.is_completed?"✓":""}</button><span className={`min-w-0 flex-1 text-sm font-medium ${item.is_completed?"line-through text-gray-400":""}`}>{item.title}</span>{item.recurrence_rule!=="none"&&<span className="text-[#8068aa]">↻</span>}<button onClick={()=>setRemoving(item)} className="rounded-lg px-2 py-1 text-xs font-semibold text-red-600 hover:bg-red-50">Remove</button></div>)}{!!selectedGoals.length&&<div className="pt-3"><p className="mb-2 text-xs font-semibold uppercase tracking-[.14em] text-[#6c8772]">Scheduled goals</p>{selectedGoals.map(goal=><div key={goal.id} className="mb-2 rounded-2xl bg-[#edf3ee] px-4 py-3 text-sm font-medium text-[#45634c]">{goal.icon||"🎯"} {goal.name}</div>)}</div>}</div>
 <div className="mt-6 border-t border-[#eeeaf3] pt-5"><h3 className="font-semibold">Add a To Do</h3><input value={task} onChange={e=>setTask(e.target.value)} placeholder="What needs to be done?" className="mt-3 w-full rounded-2xl border border-[#d9d2e5] bg-[#fbfaff] px-4 py-3.5 outline-none focus:border-[#8068aa]"/><div className="mt-3 grid gap-3 sm:grid-cols-2"><div><label className="text-xs font-semibold text-gray-600">Repeat</label><MomentumSelect placeholder="Does not repeat" value={repeat} options={[{value:"daily",label:"Every day",icon:"↻"},{value:"weekdays",label:"Weekdays",icon:"▦"},{value:"weekly",label:"Every week",icon:"↻"}]} onChange={value=>setRepeat((value||"none") as Repeat)}/></div><label className="text-xs font-semibold text-gray-600">Reminder (optional)<input type="time" value={reminder} onChange={e=>setReminder(e.target.value)} className="mt-2 block w-full rounded-2xl border border-[#d9d2e5] bg-[#fbfaff] px-4 py-3.5"/></label></div>{repeat!=="none"&&<label className="mt-3 block text-xs font-semibold text-gray-600">Repeat until<input type="date" min={selected} value={repeatUntil} onChange={e=>setRepeatUntil(e.target.value)} className="mt-2 block w-full rounded-2xl border border-[#d9d2e5] bg-[#fbfaff] px-4 py-3.5"/><span className="mt-1 block font-normal text-gray-400">Defaults to 90 days when left empty.</span></label>}<button disabled={busy||!task.trim()} onClick={addTask} className="mt-4 w-full rounded-2xl bg-[#6d5796] px-5 py-3.5 text-sm font-semibold text-white disabled:opacity-50">{busy?"Saving…":"Add to this day"}</button></div></section></div>,document.body)}
 {mounted&&removing&&createPortal(<div className="fixed inset-0 z-[60] flex items-center justify-center bg-[#18251dc0] p-5"><section role="dialog" aria-modal="true" className="w-full max-w-sm rounded-3xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-semibold">Remove “{removing.title}”?</h2>{removing.recurrence_group_id?<><p className="mt-2 text-sm text-gray-500">Choose how much of this repeating task to remove.</p><div className="mt-5 space-y-2">{[["one","Only this task"],["future","This and future tasks"],["all","Entire repeating series"]].map(([scope,label])=><button key={scope} disabled={busy} onClick={()=>remove(scope as "one"|"future"|"all")} className="w-full rounded-xl border border-[#e5dfea] px-4 py-3 text-left text-sm font-semibold hover:bg-[#faf8fc]">{label}</button>)}</div></>:<><p className="mt-2 text-sm text-gray-500">This task will be removed from your calendar.</p><button disabled={busy} onClick={()=>remove("one")} className="mt-5 w-full rounded-xl bg-red-600 px-4 py-3 text-sm font-semibold text-white">Remove task</button></>}<button disabled={busy} onClick={()=>setRemoving(null)} className="mt-2 w-full rounded-xl px-4 py-3 text-sm font-semibold text-gray-500">Cancel</button></section></div>,document.body)}
 </div></main>
}


