"use client";

import { useEffect, useId, useLayoutEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";

export type MomentumSelectOption = { value:string; label:string; icon?:string|null; detail?:string };
type Props = { id?:string; name?:string; options:MomentumSelectOption[]; placeholder:string; value?:string; defaultValue?:string; disabled?:boolean; describedBy?:string; inlineOptions?:boolean; portalOptions?:boolean; onChange?:(value:string)=>void };
type Position = { left:number; top:number; width:number; maxHeight:number };

export default function MomentumSelect({id,name,options,placeholder,value,defaultValue="",disabled=false,describedBy,inlineOptions=false,portalOptions=false,onChange}:Props){
 const generatedId=useId(),selectId=id??generatedId,listId=`${selectId}-options`;
 const [internalValue,setInternalValue]=useState(defaultValue),[open,setOpen]=useState(false),[highlighted,setHighlighted]=useState(0),[mounted,setMounted]=useState(false),[position,setPosition]=useState<Position|null>(null);
 const trigger=useRef<HTMLButtonElement>(null),menu=useRef<HTMLDivElement>(null);
 const selectedValue=value??internalValue,selected=options.find(option=>option.value===selectedValue),allOptions=[{value:"",label:placeholder,icon:null},...options];
 useEffect(()=>setMounted(true),[]);
 function updatePosition(){if(!trigger.current)return;const rect=trigger.current.getBoundingClientRect(),spaceBelow=window.innerHeight-rect.bottom-16,estimated=Math.min(288,allOptions.length*56+16),openAbove=spaceBelow<Math.min(220,estimated)&&rect.top>spaceBelow;const maxHeight=Math.max(140,Math.min(288,openAbove?rect.top-16:spaceBelow));setPosition({left:rect.left,top:openAbove?Math.max(8,rect.top-Math.min(estimated,maxHeight)-8):rect.bottom+8,width:rect.width,maxHeight})}
 useLayoutEffect(()=>{if(!open||!portalOptions)return;updatePosition();const update=()=>updatePosition();window.addEventListener("resize",update);window.addEventListener("scroll",update,true);return()=>{window.removeEventListener("resize",update);window.removeEventListener("scroll",update,true)}},[open,portalOptions,allOptions.length]);
 useEffect(()=>{if(!open||!portalOptions)return;const close=(event:PointerEvent)=>{const target=event.target as Node;if(!trigger.current?.contains(target)&&!menu.current?.contains(target))setOpen(false)};document.addEventListener("pointerdown",close);return()=>document.removeEventListener("pointerdown",close)},[open,portalOptions]);
 function choose(nextValue:string){if(value===undefined)setInternalValue(nextValue);onChange?.(nextValue);setOpen(false);trigger.current?.focus()}
 function move(amount:number){setOpen(true);setHighlighted(current=>(current+amount+allOptions.length)%allOptions.length)}
 const optionList=<div ref={menu} id={listId} role="listbox" aria-activedescendant={`${selectId}-option-${highlighted}`} style={portalOptions&&position?{position:"fixed",left:position.left,top:position.top,width:position.width,maxHeight:position.maxHeight}:undefined} className={`${portalOptions?"z-[100]":inlineOptions?"relative z-30":"absolute z-30"} ${portalOptions?"":"mt-2"} max-h-72 w-full overflow-y-auto rounded-2xl border border-[#dfe6d9] bg-white p-2 shadow-[0_18px_45px_-18px_#294d3b70]`}>{allOptions.map((option,index)=><button key={option.value||"empty"} id={`${selectId}-option-${index}`} type="button" role="option" aria-selected={option.value===selectedValue} onMouseDown={event=>event.preventDefault()} onMouseEnter={()=>setHighlighted(index)} onClick={()=>choose(option.value)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm transition ${index===highlighted?"bg-[#edf2e5]":"hover:bg-[#f5f7f1]"} ${option.value===selectedValue?"font-semibold text-[#294d3b]":"text-[#455448]"}`}><span aria-hidden="true" className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-[#f0f4e9] text-lg">{option.icon||(option.value?"🎯":"—")}</span><span className="min-w-0 flex-1 truncate">{option.label}</span>{option.detail&&<span className="rounded-full bg-white px-2 py-1 text-[10px] font-medium text-[#74816f]">{option.detail}</span>}{option.value===selectedValue&&<span aria-hidden="true" className="text-[#45634c]">✓</span>}</button>)}</div>;
 return <div className="relative" onBlur={event=>{if(!portalOptions&&!event.currentTarget.contains(event.relatedTarget))setOpen(false)}}>{name&&<input type="hidden" name={name} value={selectedValue}/>}<button ref={trigger} id={selectId} type="button" disabled={disabled} role="combobox" aria-haspopup="listbox" aria-expanded={open} aria-controls={listId} aria-describedby={describedBy} onClick={()=>{setHighlighted(Math.max(0,allOptions.findIndex(option=>option.value===selectedValue)));setOpen(current=>!current)}} onKeyDown={event=>{if(event.key==="ArrowDown"){event.preventDefault();move(1)}if(event.key==="ArrowUp"){event.preventDefault();move(-1)}if(event.key==="Enter"&&open){event.preventDefault();choose(allOptions[highlighted].value)}if(event.key==="Escape"){event.preventDefault();setOpen(false)}if(event.key==="Home"&&open){event.preventDefault();setHighlighted(0)}if(event.key==="End"&&open){event.preventDefault();setHighlighted(allOptions.length-1)}}} className="mt-2 flex min-h-[60px] w-full items-center justify-between gap-4 rounded-2xl border border-[#d4dfd2] bg-[#fafbf7] px-4 py-3 text-left text-sm text-[#233b2c] shadow-[0_3px_12px_-8px_#294d3b60] transition hover:border-[#94a98d] hover:bg-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#45634c] disabled:cursor-wait disabled:opacity-60"><span className={`flex min-w-0 items-center gap-3 ${selected?"":"text-gray-500"}`}><span aria-hidden="true" className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-[#eaf0df] text-lg">{selected?.icon||(selected?"🎯":"—")}</span><span className="truncate font-medium">{selected?.label??placeholder}</span>{selected?.detail&&<span className="shrink-0 rounded-full bg-[#edf2e5] px-2 py-1 text-[10px] text-[#61715f]">{selected.detail}</span>}</span><svg aria-hidden="true" viewBox="0 0 20 20" className={`h-4 w-4 shrink-0 fill-none stroke-current transition ${open?"rotate-180":""}`}><path d="m5 7.5 5 5 5-5" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/></svg></button>{open&&!disabled&&(portalOptions&&mounted?createPortal(optionList,document.body):optionList)}</div>
}

